language: python
python:
  - "3.4"
sudo: required
dist: trusty
services:
  - docker
before_install:
  - pip install SPARQLWrapper docker-compose
install:
  - docker-compose up -d pbg-ld
script:
  - python test.py
