language: python
python:
  - "3.4"
sudo: required
dist: trusty
services:
  - docker
before_install:
  - sudo apt-get install -y build-essential
  - pip install SPARQLWrapper
  - cd src
install:
  - travis_wait 60 make all
script:
  - python test.py
