language: python
python:
  - "3.6"
sudo: required
dist: trusty
services:
  - docker
before_install:
  - pip install docker-compose
install:
  - docker-compose up -d pbg-ld
  - sleep 180
  - docker-compose ps
script:
  - docker inspect -f '{{json .State.Health.Status}}' pbg-ld | grep healthy || exit 1